### ISSUE TITLE
No Cash Slider for Paragon Calculator

### ISSUE THREAD

**Issue by Kaister300** [Kaister300/BTD6ParagonCalculator#6]
Replace the NOTE in the paragoncal widget with a paragon cash slider which changes the current power of the paragon.

**Comment by jxu** [comment]
Also can you make the cash and pops input box unit in millions? So i can type in for example 6.5 instead of 6500000. that's how I do it mentally

**Comment by Kaister300** [comment]
Ngl, forgot I had this open. I'll find some time to work on it soon(tm)

**Comment by Kaister300** [comment]
Issue #11 is for the input box units
